language: java

# Geobuf requires Java 8 (OpenJDK 8 is not available on travis)
jdk:
  - oraclejdk8

# encrypted AWS access/secret keys to allow automated deployment to conveyal maven repo
env:
  global:
    # encrypted AWS access/secret keys to allow automated deployment to conveyal maven repo
    - secure: "o5mIHTKiJgHjYUfoHcDwElNj8eShRTqVJRNS5DTfxy+7Tnv6JcKXv4BQzJi7Lzj8kfvQz9xBmYRij2oY+t/dDDcwBfkI4WrrGL1b5pgl1HoyncXgQj0uej8C+bD3FtKJ5aD/UJx5YtbKeMTE8Yz7+IzfyW7JtgANEoMbme1yID47wlSNgfYbvEeHvQPA1RpjR7NdJvesgGt/05L2W46tacxptp5MDrqCyvytpeoWQjS8RpApACL9NoOENH4hxsxJbgjaBK6QComiymOQVSfTwi0MEWqIdbl8YBaA4c1RglRYF86BDnuOqNqsb+yO9pizWeyDJTo1T3szG4o23Wo6MqBu52QC6oPMkoED59bBATB6uDwG7uxDkpDk7BWJZkg7VFQSNDM62+gOII2mssDp49Qo2jP0wVozCGkk9mExOTUrGfwx/AVGj88ockJFIJw6y9/8GtpqwxMdsHEPKJl3/iKqt3IB4gJ4jErlowMPG4uRPO01vkjXx1wi1+lu0TCLivz1Kjgby4RPnD6THG5SP2wpYypym7jyWp7aB4AWoeULuJNN/2MYYFGxT3yo3fJ4A+Md7sQf548GN4nJC9CX4+JASTxF/ZnKOv3VS++SA8EBKyAOd57vZJZ/mRF/2RhkQtj6Y8dt1ztOR/mhXD0TmX/sLPcGvs4Y1I6TnqSCaSo="
    - secure: "i5IlkapdSkptmr1unNgYvn0Ps707OOcL9qOxlPUdz/LcHdBQWv0ajuvdvS84JgkY0OFVPVk6+CeiByUU7CbHUNLTuwubXqKoxyAx095jLZ8eG4y12SlZQOay70djgfRHCUj2YMhHqIwoXjObc3FCoUjs8xlofdvHItDQT5kwVt/MVAssXfYxTHaLwhjI4JHhWk/YKbY6pfD2RF+3DiL6RT75By7lbVuTmLZqzDgNFGxmYN+yWNiIowpTIZto651ttV20ICu5atVMryWL8uurG+/xRhari4NTnHn7Clq8MbwxXwOUDekIlUy2+GAsFGCluYZESNJ76d2lVzAjJF3jzE2Rg989KEW02v3iMYi/xu1NY75ZUpQeMS0zTCQCC1BbZq1LmKqdh8Bp69kn1CmPaBWIfG/ZncCLplTsqK6aNnCZsskcRNR/es3DW2n0GBeG/CtPkvKg79olJyCdsvowfXezb4isw1MkjSh1tIaUD5lfJ8KBmXHz0IsYBOtraQZRjwOa8Cef0YQP7v5K4F9C5YNUzEVW7RZML8OUc30qjT8xUpfmnErrVNaSMJFyKA6bppBhGAfJQLtrsjOoCTlh4JnXzkq0M4owckXOr8f+iED8q5DxWujTdIR5fA/WwsiINw82kf1D42UNEaSENor3YvzlTG2GJF90akOmpby9WO0="

# Run on container based infrastructure (allows caching &c.)
sudo: false

# deploy maven artifacts from master iff it's not a pull request
after_success: |
  if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    # no need to run tests again
    mvn deploy --settings settings.xml -DskipTests
  fi

# Save the maven cache to speed up builds
cache:
  directories:
    - "$HOME/.m2/repository"
